name: ca workflow
on:
 push:
    branches:
      - main


jobs:
    scan_repository:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
        #file checkout
        - name: checkout source
          id: checkout_source
          uses: actions/checkout@v4

        #repository scan
        - name: Trivy Scan
          id: scan_repo
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: "fs"
            ignore-unfixed: true
            format: "table"
            output: "trivy-results.txt"
            severity: "CRITICAL"
            exit-code: 1

        #Check file directory    
        # - name: Directory
        #   id: file_directory
        #   run: echo "$(ls -l)"

        # #Docker build & push
        - name: Set up QEM
          if: success()
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          if: success()
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          if: success()
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}

        - name: Build and push
          id: docker_build_push
          if: success()
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{secrets.DOCKERHUB_USERNAME}}/go_fortune:${{github.sha}}

        # cosign
        - name: Cosign-installer
          uses: sigstore/cosign-installer@v3.1.2

        - name: cosign image sign
          run: |
            cosign sign --key env://COSIGN_PRIVATEKEY "${{secrets.DOCKERHUB_USERNAME}}/go_fortune:${{github.sha}}"
          env:
            COSIGN_PRIVATEKEY: ${{secrets.COSIGN_PRIVATEKEY}}
            COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

        # slack notification if scan is successful
        - name: Slack Notification (Success)
          id: slack_notif_success
          uses: rtCamp/action-slack-notify@v2
          if: success()
          env:
            SLACK_TITLE: Image build and signed
            SLACK_MESSAGE: "*Name*: Dian \n*Metriculation:* abc123\n*Email:* abc@gmail.com\n*Git:* <${{github.repository}}>\n *Image:* <docker.com>" 
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

        # slack notification if scan has failed
        - name: Slack Notification (Fail)
          id: slack_notif_fail
          uses: rtCamp/action-slack-notify@v2
          if: failure()
          env:
            SLACK_TITLE: Scan Failed
            SLACK_MESSAGE: "Failed trivy scan. \nPlease refer to attached report."
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

        - name: Trivy File Scan Upload
          id: file_upload
          uses: MeilCli/slack-upload-file@v3
          if: failure()
          with:
            slack_token: ${{secrets.SLACK_TOKEN}}
            channel_id: ${{secrets.SLACK_CHANNELID}}
            file_path: "trivy-results.txt"
            initial_comment: "post by slack-upload-file"


