name: ca workflow
on:
- push

jobs:
    scan_repository:
        runs-on: ubuntu-latest

        steps:
        - name: checkout source
          id: checkout_source
          uses: actions/checkout@v4

        - name: Trivy Scan
          id: scan_repo
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: "fs"
            ignore-unfixed: true
            format: "table"
            output: "trvy-results.txt"
            severity: "HIGH"

        - name: Slack Notification
          id: slack_notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_TITLE: Papipopeto Pipipeti
            SLACK_USERNAME: kkuma
            SLACK_MESSAGE: "Failed trivy scan. \nPlease refer to attached report."
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
