name: ca workflow
on:
 push:
  branches:
    - 'v[0-9]+.[0-9]+'


jobs:
    scan_repository:
        runs-on: ubuntu-latest

        steps:
        #filter message
        - name: Filter Commit Message
          id: filter_message
          run: |
            message="${{ github.event.head_commit.message }}"
            if [[ $message == "#NORUN"* ]]; then
               exit 1
            fi

        #checkout
        - name: checkout source
          id: checkout_source
          uses: actions/checkout@v4

        #repository scan
        - name: Trivy Scan
          id: scan_repo
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: "fs"
            ignore-unfixed: true
            format: "table"
            output: "trivy-results.txt"
            severity: "HIGH, CRITICAL"
            exit-code: 1

        # #Docker build & push
        - name: Set up QEM
          if: success()
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          if: success()
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          if: success()
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}

        - name: Build and push
          id: docker_build_push
          if: success()
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{secrets.DOCKERHUB_USERNAME}}/go_fortune:${{github.sha}}

        # cosign
        - name: Cosign-installer
          id: cosign_install
          if: success()
          uses: sigstore/cosign-installer@v3.1.2

        - name: cosign image sign
          id: cosign_sign
          if: success()
          run: |
            cosign sign --yes --key env://COSIGN_PRIVATEKEY "${{secrets.DOCKERHUB_USERNAME}}/go_fortune:${{github.sha}}"
          env:
            TAGS: 
            COSIGN_PRIVATEKEY: ${{secrets.COSIGN_PRIVATEKEY}}
            COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

        # slack notification if scan is successful
        - name: Slack Notification (Success)
          id: slack_notif_success
          uses: rtCamp/action-slack-notify@v2
          if: success()
          env:
            SLACK_TITLE: Image build and signed
            SLACK_MESSAGE: "*Name*: Dian Kartikasari Lianto\n*Metriculation:* A0099430B\n*Email:* e1275406@u.nus.edu\n*Git:* <https://github.com/${{github.repository}}>\n *Image:* <https://hub.docker.com/repository/docker/dkl096/go_fortune/>" 
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

        # slack notification if scan has failed
        - name: Slack Notification (Fail)
          id: slack_notif_fail
          uses: rtCamp/action-slack-notify@v2
          if: failure()
          env:
            SLACK_TITLE: Scan Failed
            SLACK_MESSAGE: "Failed trivy scan. \nPlease refer to attached report."
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

        # trivy scan output upload when failed
        - name: Trivy File Scan Upload
          id: file_upload
          uses: MeilCli/slack-upload-file@v3
          if: failure()
          with:
            slack_token: ${{secrets.SLACK_TOKEN}}
            channel_id: ${{secrets.SLACK_CHANNELID}}
            file_path: "trivy-results.txt"
            initial_comment: "post by slack-upload-file"


