name: ca workflow
on:
- push

jobs:
    scan_repository:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
        - name: checkout source
          id: checkout_source
          uses: actions/checkout@v4

        - name: Trivy Scan
          id: scan_repo
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: "fs"
            ignore-unfixed: true
            format: "table"
            output: "trivy-results.txt"
            severity: "HIGH"
            exit-code: 1

        # - name: Directory
        #   id: file_directory
        #   run: echo "$(ls -l)"

        - name: Slack Notification
          id: slack_notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_TITLE: Scan Failed
            SLACK_MESSAGE: "Failed trivy scan. \nPlease refer to attached report."
            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}

        - name: Trivy File Scan Upload
          id: file_upload
          uses: MeilCli/slack-upload-file@v3
          with:
            slack_token: ${{secrets.SLACK_TOKEN}}
            channel_id: ${{secrets.SLACK_CHANNELID}}
            file_path: "trivy-results.txt"
            initial_comment: "post by slack-upload-file"


